# Generated by Django 4.2 on 2023-04-17 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_commer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=6)),
                ('laptop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_commer.laptop')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_commer.order')),
            ],
        ),
    ]
